// tests/fixtures/parity/pages/** -> build/pages.js, the corpus the phase 1
// cells serve. One module, seeds keyed by profile, pages in recording order.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', 'tests', 'fixtures', 'parity', 'pages');
const out = join(here, '..', 'build', 'pages.js');

const seeds = {};
const pages = [];
for (const profile of readdirSync(root).sort()) {
  const dir = join(root, profile);
  for (const file of readdirSync(dir).sort()) {
    const data = JSON.parse(readFileSync(join(dir, file), 'utf8'));
    if (file === 'seed.json') {
      seeds[profile] = data;
      continue;
    }
    const name = file.replace(/\.json$/, '');
    const at = name.indexOf('@');
    pages.push({ profile, name, state: at < 0 ? null : name.slice(at + 1), ...data });
  }
}
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// generated by scripts/build-pages.mjs\nexport default ${JSON.stringify({ seeds, pages })};\n`);
console.log(`pages: ${pages.length} pages, ${Object.keys(seeds).length} seeds -> ${out}`);
