#!/usr/bin/env node
// Bundles the domain modules the browser also runs into their committed
// twins under static/js. The TypeScript is the source; the twins are
// generated, dependency-free ES modules. `bundle` returns the text so
// the twin test can compare a fresh build against the committed file.
import { writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

export const WORKER = fileURLToPath(new URL("..", import.meta.url));
export const REPO = join(WORKER, "..");

export const TWINS = [
  { entry: "domain/markdown/index.ts", out: "static/js/study/markdown.js" },
  { entry: "domain/grading/client.ts", out: "static/js/offline/grader.js" },
];

export async function bundle(entry) {
  const banner = `// generated by worker/scripts/build-domain.mjs from worker/${entry}; do not edit`;
  const result = await esbuild.build({
    entryPoints: [join(WORKER, entry)],
    bundle: true,
    format: "esm",
    target: "es2022",
    charset: "utf8",
    minify: false,
    write: false,
    logLevel: "silent",
    banner: { js: banner },
  });
  return result.outputFiles[0].text;
}

// `only`: substrings of the twin's output path; empty builds every twin.
export async function buildTwins(repo = REPO, only = []) {
  const written = [];
  for (const twin of TWINS) {
    if (only.length && !only.some((s) => twin.out.includes(s))) continue;
    writeFileSync(join(repo, twin.out), await bundle(twin.entry));
    written.push(twin.out);
  }
  return written;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  buildTwins(REPO, process.argv.slice(2))
    .then((written) => {
      for (const out of written) console.log(`domain twin: ${relative(REPO, join(REPO, out))}`);
    })
    .catch((e) => {
      console.error(`build-domain failed: ${e.message ?? e}`);
      process.exit(1);
    });
}
