#!/usr/bin/env node
// Bakes everything the worker imports from build/ and lays out dist/assets.
// Each step is a function so tests can run one against a scratch tree;
// `main` runs them in order. build/ and dist/ are never committed.
import { execFileSync, spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import nunjucks from "nunjucks";
import { resolveToken } from "../runtime/tokenRules.ts";

export const WORKER = fileURLToPath(new URL("..", import.meta.url));
export const REPO = join(WORKER, "..");
export const BUILD = join(WORKER, "build");
export const DIST_ASSETS = join(WORKER, "dist", "assets");
export const STATIC = join(REPO, "static");
export const TEMPLATES = join(WORKER, "templates");

// Directories under static/ that are build inputs, not served assets.
const STATIC_EXCLUDED_DIRS = new Set(["mockups", "cm"]);
// Served rendered by the /sw.js route, never as a plain file.
const STATIC_EXCLUDED_FILES = new Set(["sw.js"]);

// static/js subtrees the offline shell needs, in manifest order.
const PRECACHE_JS_DIRS = ["offline", "study", "dashboard", "modules"];

// Every file under `dir`, as posix paths relative to it, in Python's
// pathlib order: paths compare component by component, which differs
// from a plain string sort whenever a directory name is a prefix of a
// sibling file name.
export function walk(dir) {
  const out = [];
  (function visit(d) {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) visit(p);
      else out.push(relative(dir, p).split(sep));
    }
  })(dir);
  out.sort(compareParts);
  return out.map((parts) => parts.join("/"));
}

function compareParts(a, b) {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return a.length - b.length;
}

// 1. templates/** to build/templates.js for the nunjucks-slim runtime.
export function precompileTemplates(templatesDir, outDir) {
  const env = new nunjucks.Environment(null, { autoescape: true });
  const entries = [];
  for (const name of walk(templatesDir)) {
    if (!name.endsWith(".html")) continue;
    let js;
    try {
      js = nunjucks.precompileString(readFileSync(join(templatesDir, name), "utf8"), {
        name,
        env,
        wrapper: (templates) => templates.map((t) => `(function() {${t.template}})()`).join("\n"),
      });
    } catch (e) {
      throw new Error(`template ${name} does not precompile: ${String(e.message ?? e).split("\n")[0]}`);
    }
    entries.push(`  ${JSON.stringify(name)}: ${js},`);
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "templates.js"), `// generated by scripts/build.mjs\nexport default {\n${entries.join("\n")}\n};\n`);
  writeFileSync(join(outDir, "templates.d.ts"), "declare const templates: Record<string, unknown>;\nexport default templates;\n");
  return entries.length;
}

// 2. static/icons/*.svg to build/icons.js, name to trimmed source.
export function bakeIcons(iconsDir, outDir) {
  const icons = {};
  for (const name of walk(iconsDir)) {
    if (!name.endsWith(".svg") || name.includes("/")) continue;
    icons[basename(name, ".svg")] = readFileSync(join(iconsDir, name), "utf8").trim();
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "icons.js"), `// generated by scripts/build.mjs\nexport default ${JSON.stringify(icons, null, 2)};\n`);
  writeFileSync(join(outDir, "icons.d.ts"), "declare const icons: Record<string, string>;\nexport default icons;\n");
  return Object.keys(icons).length;
}

// The relative asset paths the service worker precaches, in manifest
// order: the whole css tree, then the four js subtrees in a fixed order.
export function precacheTree(staticDir) {
  const css = walk(join(staticDir, "css"));
  const js = [];
  for (const sub of PRECACHE_JS_DIRS) {
    const subdir = join(staticDir, "js", sub);
    if (!existsSync(subdir)) continue;
    for (const rel of walk(subdir)) js.push(`${sub}/${rel}`);
  }
  return { css, js };
}

// 3. static/sw.js and the precache enumeration to build/sw.js.
export function bakeServiceWorker(staticDir, outDir) {
  const tree = precacheTree(staticDir);
  const source = readFileSync(join(staticDir, "sw.js"), "utf8");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    join(outDir, "sw.js"),
    `// generated by scripts/build.mjs\nexport const SW_SOURCE = ${JSON.stringify(source)};\nexport const ASSET_TREE = ${JSON.stringify(tree)};\n`,
  );
  return tree;
}

// 4. PREP_BUILD_ID (default: the git HEAD) through the token rules into
// build/buildinfo.js.
export function bakeBuildInfo(raw, outDir) {
  const head = execFileSync("git", ["rev-parse", "HEAD"], { cwd: WORKER, encoding: "utf8" }).trim();
  const token = resolveToken(raw, head);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "buildinfo.js"), `// generated by scripts/build.mjs\nexport const BUILD_TOKEN = ${JSON.stringify(token)};\n`);
  return token;
}

// 5. static/ to dist/assets/static/, minus the build inputs.
export function copyStatic(staticDir, distAssetsDir) {
  const dest = join(distAssetsDir, "static");
  rmSync(dest, { recursive: true, force: true });
  mkdirSync(distAssetsDir, { recursive: true });
  cpSync(staticDir, dest, {
    recursive: true,
    filter: (src) => {
      const rel = relative(staticDir, src);
      if (rel === "") return true;
      const top = rel.split(sep)[0];
      if (STATIC_EXCLUDED_DIRS.has(top)) return false;
      if (rel === top && STATIC_EXCLUDED_FILES.has(top)) return false;
      return true;
    },
  });
  return walk(dest).length;
}

// 6. scripts/render-fixtures.mjs bundled for node, so the DOM gate runs
// the same shims and view models the worker ships.
export async function bundleRenderFixtures(entry, outDir) {
  if (!existsSync(entry)) throw new Error(`${relative(WORKER, entry)} is missing`);
  mkdirSync(outDir, { recursive: true });
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node20",
    outfile: join(outDir, "render-fixtures.cjs"),
    logLevel: "silent",
  });
}

// 7. tsc --noEmit over worker/ and worker/tests/.
export function typecheck() {
  for (const project of ["tsconfig.json", "tests/tsconfig.json"]) {
    const r = spawnSync(join(WORKER, "node_modules", ".bin", "tsc"), ["-p", project, "--noEmit"], {
      cwd: WORKER,
      stdio: "inherit",
    });
    if (r.status !== 0) throw new Error(`tsc -p ${project} failed`);
  }
}

async function main() {
  const n = precompileTemplates(TEMPLATES, BUILD);
  console.log(`templates: ${n} precompiled`);
  console.log(`icons: ${bakeIcons(join(STATIC, "icons"), BUILD)}`);
  const tree = bakeServiceWorker(STATIC, BUILD);
  console.log(`sw: ${tree.css.length} css + ${tree.js.length} js precache entries`);
  console.log(`build token: ${bakeBuildInfo(process.env.PREP_BUILD_ID, BUILD)}`);
  console.log(`assets: ${copyStatic(STATIC, DIST_ASSETS)} files under dist/assets/static`);
  await bundleRenderFixtures(join(WORKER, "scripts", "render-fixtures.mjs"), BUILD);
  console.log("render-fixtures: bundled");
  typecheck();
  console.log("typecheck: ok");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((e) => {
    console.error(`build failed: ${e.message ?? e}`);
    process.exit(1);
  });
}
