import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { REPO, TWINS, WORKER, bundle } from "../../scripts/build-domain.mjs";

// The committed browser twins are exactly what a fresh build emits, so an
// edit to the TypeScript without `npm run build:domain` fails here. A twin
// that has never been generated (no build banner) is not pinned yet.
describe("domain twins are fresh", () => {
  for (const twin of TWINS) {
    it(`${twin.out} is the build of ${twin.entry}`, async () => {
      if (!existsSync(join(WORKER, twin.entry))) return;
      const committed = readFileSync(join(REPO, twin.out), "utf8");
      if (!committed.startsWith("// generated by worker/scripts/build-domain.mjs")) return;
      expect(await bundle(twin.entry)).toBe(committed);
    });
  }
  it("pins the markdown twin", () => {
    expect(readFileSync(join(REPO, "static/js/study/markdown.js"), "utf8")).toMatch(/^\/\/ generated by/);
  });
});
