import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { REPO, TWINS, bundle } from "../../scripts/build-domain.mjs";

// The committed browser twins are exactly what a fresh build emits, so an
// edit to the TypeScript without `npm run build:domain` fails here, and so
// does a twin that was never generated.
describe("domain twins are fresh", () => {
  it("pins both twins", () => {
    expect(TWINS.map((t) => t.out).sort()).toEqual(["static/js/offline/grader.js", "static/js/study/markdown.js"]);
  });
  for (const twin of TWINS) {
    it(`${twin.out} is the build of ${twin.entry}`, async () => {
      const committed = readFileSync(join(REPO, twin.out), "utf8");
      expect(committed).toMatch(/^\/\/ generated by worker\/scripts\/build-domain\.mjs/);
      expect(await bundle(twin.entry)).toBe(committed);
    });
  }
});
