// Precompiles every template under ./templates into one ESM module for the
// nunjucks-slim runtime. A template that fails to parse is reported and
// skipped so the rest still bundles.
import { readdirSync, statSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import nunjucks from 'nunjucks';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, 'templates');
const files = [];
(function walk(d) {
  for (const e of readdirSync(d)) {
    const p = join(d, e);
    if (statSync(p).isDirectory()) walk(p);
    else if (e.endsWith('.html')) files.push(p);
  }
})(root);

const env = new nunjucks.Environment(null, { autoescape: true });
const out = [];
const failed = [];
for (const f of files.sort()) {
  const name = relative(root, f);
  try {
    const js = nunjucks.precompileString(readFileSync(f, 'utf8'), {
      name,
      env,
      wrapper: (templates) => templates.map((t) => `(function() {${t.template}})()`).join("\n"),
    });
    out.push(`  ${JSON.stringify(name)}: ${js},`);
  } catch (e) {
    failed.push({ name, error: String(e.message ?? e).split('\n')[0].slice(0, 160) });
  }
}
mkdirSync(join(here, 'build'), { recursive: true });
writeFileSync(join(here, 'build', 'templates.js'), `// generated by precompile.mjs\nexport default {\n${out.join('\n')}\n};\n`);
console.log(`compiled ${out.length}/${files.length}`);
for (const f of failed) console.log(`  FAIL ${f.name}: ${f.error}`);
